server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka