server:
  port: 8082
spring:
  application:
    name: note-service
  config:
    import: configserver:http://localhost:8888


cloud:
  stream:
    bindings:
      personUpdatedEventConsumer-in-0:
      destination: person-topic
      group: person-event-queue

