server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://C:\PROGRAMS\test programs\microservices\config-service\src\main\resources\config

